# Generated by Django 2.1.5 on 2020-08-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.TextField(default='#'),
            preserve_default=False,
        ),
    ]
