# Generated by Django 2.1.5 on 2020-08-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_blog', '0002_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.TextField(default='uploads/default'),
        ),
    ]
