# Generated by Django 2.1.5 on 2020-08-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_blog', '0003_auto_20200817_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.TextField(default='https://www.pngkey.com/png/detail/516-5169774_iif-internships-icon.png'),
        ),
    ]
